add udev-builtin-path_id property to zfcp-attached SCSI disks
storaged-project/blivet pull request #1161
Opened 2023-10-13 16:24 UTC by steffen-maier

so anaconda can use it to display path_id information for multipath members

**Note**:
It would be nice to get this into RHEL9.x as well, but I'm not sure which branch I should base my PR according to CONTRIBUTING ("oldest ``x.y`` release that should include
your work"). So for starters I tried to use the latest branch for upstreaming.

@jstodola @poncovka @sharkcz

2023-10-13 16:27 UTC, StorageGhoul commented
Can one of the admins verify this patch?

2023-10-16 09:09 UTC, vojtechtrefny commented
Jenkins, ok to test.

2023-10-16 09:25 UTC, vojtechtrefny requested changes
Looks good to me. Thank you. Some tests that create "fake" `ZFCPDiskDevice` devices needs to be fixed to include the new `id_path` argument before we can merge this: [Anaconda](https://github.com/rhinstaller/anaconda/blob/fdd73fa33059a3ce05fbaf0573cabb991eacde22/tests/unit_tests/pyanaconda_tests/modules/storage/test_module_device_tree.py#L249) and [Blivet](https://github.com/storaged-project/blivet/blob/57f1382f19a1390dd2176e4f4772bab89380cfdf/tests/unit_tests/tags_test.py#L75).

2023-10-16 16:44 UTC, steffen-maier commented
> Looks good to me. Thank you. Some tests that create "fake" `ZFCPDiskDevice` devices needs to be fixed to include the new `id_path` argument before we can merge this: [Anaconda](https://github.com/rhinstaller/anaconda/blob/fdd73fa33059a3ce05fbaf0573cabb991eacde22/tests/unit_tests/pyanaconda_tests/modules/storage/test_module_device_tree.py#L249) and [Blivet](https://github.com/storaged-project/blivet/blob/57f1382f19a1390dd2176e4f4772bab89380cfdf/tests/unit_tests/tags_test.py#L75).

Thanks a lot for the hints. Much appreciated, because I'm not familiar with the unit tests and am overwhelmed by all the automated checks in the git workflows.

I hope I got it right:
e695cde6065bd301e5db7e890e580264bd470bf3 for blivet here
and https://github.com/rhinstaller/anaconda/pull/5249/commits/3b159b96249c2f5b742b59e6b9c00661a800cfe8 for anaconda in the related PR.

Please let me know when I should squash my fixup commits before merging.

2023-10-17 10:58 UTC, vojtechtrefny commented
> Please let me know when I should squash my fixup commits before merging.

Yes, please squash the changes into the original commit.

2023-10-20 06:39 UTC, vojtechtrefny approved these changes
Looks good to me now, thank you.

2023-12-06 13:43 UTC, steffen-maier commented
Friendly ping.
Have I missed something in order to merge this?

2023-12-06 13:54 UTC, vojtechtrefny commented
I am waiting for Anaconda, https://github.com/rhinstaller/anaconda/pull/5249 is not acked yet and we need to coordinate merging and releasing this. But from blivet side, this is ready to be merged.

2023-12-08 13:12 UTC, rvykydal commented
> I am waiting for Anaconda, [rhinstaller/anaconda#5249](https://github.com/rhinstaller/anaconda/pull/5249) is not acked yet and we need to coordinate merging and releasing this. But from blivet side, this is ready to be merged.

https://github.com/rhinstaller/anaconda/pull/5249#issuecomment-1847145655

2023-12-12 07:12 UTC, merged